package com.sp.Table;

public enum DataType {
    SMALLINT,
    INTEGER,
    BIGINT,
    CHARACTER,
    CHARACTER_VARYING,
    TEXT,
    TIMESTAMP_WITH_TIMEZONE,
    TIMESTAMP_WITHOUT_TIMEZONE,
    DATE,
    DOUBLE_PRECISION,
    BOOLEAN,
    UUID,
    JSONB,
    UNKNOWN
}
