--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5
-- Dumped by pg_dump version 14.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Consultation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Consultation" (
    "consultationPK" integer NOT NULL,
    "patientHeight" double precision,
    "patientWeight" double precision,
    "patientBloodPressure" character varying(20),
    "consultationTimeStamp" timestamp with time zone,
    is_synced boolean NOT NULL,
    "doctorFK_id" integer NOT NULL,
    "patientFK_id" uuid NOT NULL
);


-- ALTER TABLE public."Consultation" OWNER TO postgres;

--
-- Name: Consultation_consultationPK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Consultation" ALTER COLUMN "consultationPK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Consultation_consultationPK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Department; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Department" (
    "departmentPK" integer NOT NULL,
    "departmentName" character varying(50) NOT NULL,
    is_synced boolean NOT NULL,
    "hospitalFK_id" integer NOT NULL
);


-- ALTER TABLE public."Department" OWNER TO postgres;

--
-- Name: Department_departmentPK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Department" ALTER COLUMN "departmentPK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Department_departmentPK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Diagnosis; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Diagnosis" (
    "diagonsisPK" integer NOT NULL,
    description character varying(300),
    "provisionalOrFinal" boolean NOT NULL,
    is_synced boolean NOT NULL,
    "diseaseFK_id" integer NOT NULL,
    "prescriptionFK_id" integer NOT NULL
);


-- ALTER TABLE public."Diagnosis" OWNER TO postgres;

--
-- Name: Diagnosis_diagonsisPK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Diagnosis" ALTER COLUMN "diagonsisPK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Diagnosis_diagonsisPK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Disease; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Disease" (
    "diseasePK" integer NOT NULL,
    "diseaseName" character varying(50) NOT NULL,
    is_synced boolean NOT NULL
);


-- ALTER TABLE public."Disease" OWNER TO postgres;

--
-- Name: DiseaseParam; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."DiseaseParam" (
    "diseaseParamPK" integer NOT NULL,
    "diseaseParamName" character varying(200) NOT NULL,
    is_synced boolean NOT NULL,
    "diseaseFK_id" integer NOT NULL,
    "paramNumber" character varying(6) NOT NULL,
    tab smallint NOT NULL,
    CONSTRAINT "DiseaseParam_tab_check" CHECK ((tab >= 0))
);


-- ALTER TABLE public."DiseaseParam" OWNER TO postgres;

--
-- Name: DiseaseParamData; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."DiseaseParamData" (
    "diseaseParamDataPK" integer NOT NULL,
    is_synced boolean NOT NULL,
    "diseaseParamFK_id" integer NOT NULL,
    "boolData" boolean NOT NULL,
    "diseaseParamDataName" character varying(200) NOT NULL,
    "floatData" boolean NOT NULL,
    "stringData" boolean NOT NULL,
    "tableData" boolean NOT NULL,
    "timeData" boolean NOT NULL,
    "multiBoolData" boolean NOT NULL
);


-- ALTER TABLE public."DiseaseParamData" OWNER TO postgres;

--
-- Name: DiseaseParamData_diseaseParamDataPK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."DiseaseParamData" ALTER COLUMN "diseaseParamDataPK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DiseaseParamData_diseaseParamDataPK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: DiseaseParam_diseaseParamPK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."DiseaseParam" ALTER COLUMN "diseaseParamPK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DiseaseParam_diseaseParamPK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Disease_diseasePK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Disease" ALTER COLUMN "diseasePK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Disease_diseasePK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Doctor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Doctor" (
    "doctorPK" integer NOT NULL,
    "doctorName" character varying(50) NOT NULL,
    "isHOD" boolean NOT NULL,
    is_synced boolean NOT NULL,
    "departmentFK_id" integer NOT NULL
);


-- ALTER TABLE public."Doctor" OWNER TO postgres;

--
-- Name: Doctor_doctorPK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Doctor" ALTER COLUMN "doctorPK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Doctor_doctorPK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Hospital; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Hospital" (
    "hospitalPK" integer NOT NULL,
    "hospitalName" character varying(50) NOT NULL,
    is_synced boolean NOT NULL,
    "locationFK_id" integer NOT NULL
);


-- ALTER TABLE public."Hospital" OWNER TO postgres;

--
-- Name: Hospital_hospitalPK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Hospital" ALTER COLUMN "hospitalPK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Hospital_hospitalPK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: InOutPatient; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."InOutPatient" (
    "inOutPatientPK" integer NOT NULL,
    "isInPatient" boolean NOT NULL,
    "opdUnitNo" integer,
    "wardNo" integer,
    "bedNo" integer,
    "startDate" date,
    "endDate" date,
    "nextInOutFK" integer,
    is_synced boolean NOT NULL,
    "patientFK_id" uuid NOT NULL
);


-- ALTER TABLE public."InOutPatient" OWNER TO postgres;

--
-- Name: InOutPatient_inOutPatientPK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."InOutPatient" ALTER COLUMN "inOutPatientPK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."InOutPatient_inOutPatientPK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Lab; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Lab" (
    "labPK" integer NOT NULL,
    "labName" character varying(100) NOT NULL,
    is_synced boolean NOT NULL,
    "hospitalFK_id" integer,
    "locationFK_id" integer
);


-- ALTER TABLE public."Lab" OWNER TO postgres;

--
-- Name: Lab_labPK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Lab" ALTER COLUMN "labPK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Lab_labPK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Location; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Location" (
    "locationPK" integer NOT NULL,
    state character varying(50),
    district character varying(50),
    city character varying(50),
    pin integer,
    is_synced boolean NOT NULL
);


-- ALTER TABLE public."Location" OWNER TO postgres;

--
-- Name: Location_locationPK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Location" ALTER COLUMN "locationPK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Location_locationPK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Medicine; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Medicine" (
    "medicinePK" integer NOT NULL,
    "medicineName" character varying(50) NOT NULL,
    is_synced boolean NOT NULL
);


-- ALTER TABLE public."Medicine" OWNER TO postgres;

--
-- Name: Medicine_medicinePK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Medicine" ALTER COLUMN "medicinePK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Medicine_medicinePK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Patient; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Patient" (
    "patientPK" uuid NOT NULL,
    "patientName" character varying(50) NOT NULL,
    gender character varying(8) NOT NULL,
    "fatherName" character varying(50),
    mobile character varying(50),
    email character varying(50),
    dob date NOT NULL,
    "registrationNo" integer NOT NULL,
    is_synced boolean NOT NULL,
    "patientHistory" jsonb
);


-- ALTER TABLE public."Patient" OWNER TO postgres;

--
-- Name: PatientDiseaseParamData; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PatientDiseaseParamData" (
    "patientDiseaseParamDataPK" integer NOT NULL,
    "floatParamData" double precision,
    "boolParamData" boolean,
    "stringParamData" character varying(300),
    "tableParamData" jsonb,
    "diseaseParamTimestamp" timestamp with time zone,
    is_synced boolean NOT NULL,
    "diseaseParamDataFK_id" integer NOT NULL,
    "patientFK_id" uuid NOT NULL
);


-- ALTER TABLE public."PatientDiseaseParamData" OWNER TO postgres;

--
-- Name: PatientDiseaseParamData_patientDiseaseParamDataPK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PatientDiseaseParamData" ALTER COLUMN "patientDiseaseParamDataPK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PatientDiseaseParamData_patientDiseaseParamDataPK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Patient_languages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Patient_languages" (
    id bigint NOT NULL,
    patient_id uuid NOT NULL,
    language_id character varying(50) NOT NULL
);


-- ALTER TABLE public."Patient_languages" OWNER TO postgres;

--
-- Name: Patient_languages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Patient_languages" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Patient_languages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PrescribedMedicine; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PrescribedMedicine" (
    "prescribedMedicinePK" integer NOT NULL,
    "numDays" integer,
    comments jsonb,
    is_synced boolean NOT NULL,
    "medicineFK_id" integer NOT NULL,
    "prescriptionFK_id" integer NOT NULL
);


-- ALTER TABLE public."PrescribedMedicine" OWNER TO postgres;

--
-- Name: PrescribedMedicine_prescribedMedicinePK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PrescribedMedicine" ALTER COLUMN "prescribedMedicinePK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PrescribedMedicine_prescribedMedicinePK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PrescribedTest; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PrescribedTest" (
    "prescribedTestPK" integer NOT NULL,
    is_synced boolean NOT NULL,
    "prescriptionFK_id" integer NOT NULL,
    "testFK_id" integer NOT NULL
);


-- ALTER TABLE public."PrescribedTest" OWNER TO postgres;

--
-- Name: PrescribedTest_prescribedTestPK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PrescribedTest" ALTER COLUMN "prescribedTestPK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PrescribedTest_prescribedTestPK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Prescription; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Prescription" (
    "prescriptionPK" integer NOT NULL,
    comments text,
    file character varying(250),
    is_synced boolean NOT NULL,
    "consultationFK_id" integer NOT NULL
);


-- ALTER TABLE public."Prescription" OWNER TO postgres;

--
-- Name: Prescription_prescriptionPK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Prescription" ALTER COLUMN "prescriptionPK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Prescription_prescriptionPK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ReferenceRange; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ReferenceRange" (
    "referenceRangePK" integer NOT NULL,
    gender character varying(10),
    "startAge" integer,
    "endAge" integer,
    "minValue" double precision,
    "maxValue" double precision,
    is_synced boolean NOT NULL,
    "testParamFK_id" integer NOT NULL
);


-- ALTER TABLE public."ReferenceRange" OWNER TO postgres;

--
-- Name: ReferenceRange_referenceRangePK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ReferenceRange" ALTER COLUMN "referenceRangePK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ReferenceRange_referenceRangePK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Report; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Report" (
    "reportPK" integer NOT NULL,
    "reportTimeStamp" timestamp with time zone,
    pdf character varying(100),
    is_synced boolean NOT NULL,
    "prescriptionFK_id" integer NOT NULL,
    "testFK_id" integer NOT NULL
);


-- ALTER TABLE public."Report" OWNER TO postgres;

--
-- Name: ReportParamData; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ReportParamData" (
    "reportParamFK" integer NOT NULL,
    "floatParamData" double precision,
    "boolParamData" boolean,
    "stringParamData" jsonb,
    "imageParamData" boolean NOT NULL,
    "tableParamData" jsonb,
    is_synced boolean NOT NULL,
    "reportFK_id" integer NOT NULL,
    "testParamFK_id" integer NOT NULL,
    "fileParamData" character varying(100)
);


-- ALTER TABLE public."ReportParamData" OWNER TO postgres;

--
-- Name: ReportParamData_reportParamFK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ReportParamData" ALTER COLUMN "reportParamFK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ReportParamData_reportParamFK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Report_reportPK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Report" ALTER COLUMN "reportPK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Report_reportPK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Residence; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Residence" (
    "residencePK" integer NOT NULL,
    "startDate" date,
    "endDate" date,
    is_synced boolean NOT NULL,
    "patientFK_id" uuid NOT NULL,
    location jsonb NOT NULL
);


-- ALTER TABLE public."Residence" OWNER TO postgres;

--
-- Name: Residence_residencePK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Residence" ALTER COLUMN "residencePK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Residence_residencePK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Test; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Test" (
    "testPK" integer NOT NULL,
    "testName" character varying(100) NOT NULL,
    is_synced boolean NOT NULL,
    "labFK_id" integer
);


-- ALTER TABLE public."Test" OWNER TO postgres;

--
-- Name: TestParam; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TestParam" (
    "testParamPK" integer NOT NULL,
    "testParamName" character varying(50) NOT NULL,
    "paramType" character varying(50) NOT NULL,
    is_synced boolean NOT NULL,
    "testFK_id" integer NOT NULL
);


-- ALTER TABLE public."TestParam" OWNER TO postgres;

--
-- Name: TestParam_testParamPK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TestParam" ALTER COLUMN "testParamPK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TestParam_testParamPK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Test_testPK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Test" ALTER COLUMN "testPK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Test_testPK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Treatment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Treatment" (
    "treatmentPK" integer NOT NULL,
    "startDate" date NOT NULL,
    "endDate" date,
    is_synced boolean NOT NULL,
    "medicineFK_id" integer NOT NULL,
    "patientFK_id" uuid NOT NULL
);


-- ALTER TABLE public."Treatment" OWNER TO postgres;

--
-- Name: Treatment_treatmentPK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Treatment" ALTER COLUMN "treatmentPK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Treatment_treatmentPK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


-- ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


-- ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


-- ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


-- ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


-- ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


-- ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


-- ALTER TABLE public.authtoken_token OWNER TO postgres;

--
-- Name: batch_job_execution; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.batch_job_execution (
    job_execution_id bigint NOT NULL,
    version bigint,
    job_instance_id bigint NOT NULL,
    create_time timestamp without time zone NOT NULL,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    status character varying(10),
    exit_code character varying(2500),
    exit_message character varying(2500),
    last_updated timestamp without time zone,
    job_configuration_location character varying(2500)
);


-- ALTER TABLE public.batch_job_execution OWNER TO postgres;

--
-- Name: batch_job_execution_context; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.batch_job_execution_context (
    job_execution_id bigint NOT NULL,
    short_context character varying(2500) NOT NULL,
    serialized_context text
);


-- ALTER TABLE public.batch_job_execution_context OWNER TO postgres;

--
-- Name: batch_job_execution_params; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.batch_job_execution_params (
    job_execution_id bigint NOT NULL,
    type_cd character varying(6) NOT NULL,
    key_name character varying(100) NOT NULL,
    string_val character varying(250),
    date_val timestamp without time zone,
    long_val bigint,
    double_val double precision,
    identifying character(1) NOT NULL
);


-- ALTER TABLE public.batch_job_execution_params OWNER TO postgres;

--
-- Name: batch_job_execution_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.batch_job_execution_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


-- ALTER TABLE public.batch_job_execution_seq OWNER TO postgres;

--
-- Name: batch_job_instance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.batch_job_instance (
    job_instance_id bigint NOT NULL,
    version bigint,
    job_name character varying(100) NOT NULL,
    job_key character varying(32) NOT NULL
);


-- ALTER TABLE public.batch_job_instance OWNER TO postgres;

--
-- Name: batch_job_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.batch_job_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


-- ALTER TABLE public.batch_job_seq OWNER TO postgres;

--
-- Name: batch_step_execution; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.batch_step_execution (
    step_execution_id bigint NOT NULL,
    version bigint NOT NULL,
    step_name character varying(100) NOT NULL,
    job_execution_id bigint NOT NULL,
    start_time timestamp without time zone NOT NULL,
    end_time timestamp without time zone,
    status character varying(10),
    commit_count bigint,
    read_count bigint,
    filter_count bigint,
    write_count bigint,
    read_skip_count bigint,
    write_skip_count bigint,
    process_skip_count bigint,
    rollback_count bigint,
    exit_code character varying(2500),
    exit_message character varying(2500),
    last_updated timestamp without time zone
);


-- ALTER TABLE public.batch_step_execution OWNER TO postgres;

--
-- Name: batch_step_execution_context; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.batch_step_execution_context (
    step_execution_id bigint NOT NULL,
    short_context character varying(2500) NOT NULL,
    serialized_context text
);


-- ALTER TABLE public.batch_step_execution_context OWNER TO postgres;

--
-- Name: batch_step_execution_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.batch_step_execution_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


-- ALTER TABLE public.batch_step_execution_seq OWNER TO postgres;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


-- ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


-- ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


-- ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


-- ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: patients_language; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.patients_language (
    name character varying(50) NOT NULL
);


-- ALTER TABLE public.patients_language OWNER TO postgres;

--
-- Name: tests_reportimage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tests_reportimage (
    "reportImagePK" integer NOT NULL,
    image character varying(100) NOT NULL,
    is_synced boolean NOT NULL,
    "reportParamFK_id" integer NOT NULL
);


-- ALTER TABLE public.tests_reportimage OWNER TO postgres;

--
-- Name: tests_reportimage_reportImagePK_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tests_reportimage ALTER COLUMN "reportImagePK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."tests_reportimage_reportImagePK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tests_uploadedexcel; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tests_uploadedexcel (
    id bigint NOT NULL,
    excel character varying(100) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL
);


-- ALTER TABLE public.tests_uploadedexcel OWNER TO postgres;

--
-- Name: tests_uploadedexcel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tests_uploadedexcel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tests_uploadedexcel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Consultation Consultation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Consultation"
    ADD CONSTRAINT "Consultation_pkey" PRIMARY KEY ("consultationPK");


--
-- Name: Department Department_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Department"
    ADD CONSTRAINT "Department_pkey" PRIMARY KEY ("departmentPK");


--
-- Name: Diagnosis Diagnosis_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Diagnosis"
    ADD CONSTRAINT "Diagnosis_pkey" PRIMARY KEY ("diagonsisPK");


--
-- Name: DiseaseParamData DiseaseParamData_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DiseaseParamData"
    ADD CONSTRAINT "DiseaseParamData_pkey" PRIMARY KEY ("diseaseParamDataPK");


--
-- Name: DiseaseParam DiseaseParam_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DiseaseParam"
    ADD CONSTRAINT "DiseaseParam_pkey" PRIMARY KEY ("diseaseParamPK");


--
-- Name: Disease Disease_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Disease"
    ADD CONSTRAINT "Disease_pkey" PRIMARY KEY ("diseasePK");


--
-- Name: Doctor Doctor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Doctor"
    ADD CONSTRAINT "Doctor_pkey" PRIMARY KEY ("doctorPK");


--
-- Name: Hospital Hospital_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Hospital"
    ADD CONSTRAINT "Hospital_pkey" PRIMARY KEY ("hospitalPK");


--
-- Name: InOutPatient InOutPatient_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."InOutPatient"
    ADD CONSTRAINT "InOutPatient_pkey" PRIMARY KEY ("inOutPatientPK");


--
-- Name: Lab Lab_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Lab"
    ADD CONSTRAINT "Lab_pkey" PRIMARY KEY ("labPK");


--
-- Name: Location Location_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Location"
    ADD CONSTRAINT "Location_pkey" PRIMARY KEY ("locationPK");


--
-- Name: Medicine Medicine_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Medicine"
    ADD CONSTRAINT "Medicine_pkey" PRIMARY KEY ("medicinePK");


--
-- Name: PatientDiseaseParamData PatientDiseaseParamData_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatientDiseaseParamData"
    ADD CONSTRAINT "PatientDiseaseParamData_pkey" PRIMARY KEY ("patientDiseaseParamDataPK");


--
-- Name: Patient_languages Patient_languages_patient_id_language_id_a6754cfb_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Patient_languages"
    ADD CONSTRAINT "Patient_languages_patient_id_language_id_a6754cfb_uniq" UNIQUE (patient_id, language_id);


--
-- Name: Patient_languages Patient_languages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Patient_languages"
    ADD CONSTRAINT "Patient_languages_pkey" PRIMARY KEY (id);


--
-- Name: Patient Patient_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Patient"
    ADD CONSTRAINT "Patient_pkey" PRIMARY KEY ("patientPK");


--
-- Name: PrescribedMedicine PrescribedMedicine_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PrescribedMedicine"
    ADD CONSTRAINT "PrescribedMedicine_pkey" PRIMARY KEY ("prescribedMedicinePK");


--
-- Name: PrescribedTest PrescribedTest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PrescribedTest"
    ADD CONSTRAINT "PrescribedTest_pkey" PRIMARY KEY ("prescribedTestPK");


--
-- Name: Prescription Prescription_consultationFK_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Prescription"
    ADD CONSTRAINT "Prescription_consultationFK_id_key" UNIQUE ("consultationFK_id");


--
-- Name: Prescription Prescription_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Prescription"
    ADD CONSTRAINT "Prescription_pkey" PRIMARY KEY ("prescriptionPK");


--
-- Name: ReferenceRange ReferenceRange_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ReferenceRange"
    ADD CONSTRAINT "ReferenceRange_pkey" PRIMARY KEY ("referenceRangePK");


--
-- Name: ReportParamData ReportParamData_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ReportParamData"
    ADD CONSTRAINT "ReportParamData_pkey" PRIMARY KEY ("reportParamFK");


--
-- Name: Report Report_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Report"
    ADD CONSTRAINT "Report_pkey" PRIMARY KEY ("reportPK");


--
-- Name: Residence Residence_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Residence"
    ADD CONSTRAINT "Residence_pkey" PRIMARY KEY ("residencePK");


--
-- Name: TestParam TestParam_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TestParam"
    ADD CONSTRAINT "TestParam_pkey" PRIMARY KEY ("testParamPK");


--
-- Name: Test Test_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Test"
    ADD CONSTRAINT "Test_pkey" PRIMARY KEY ("testPK");


--
-- Name: Treatment Treatment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Treatment"
    ADD CONSTRAINT "Treatment_pkey" PRIMARY KEY ("treatmentPK");


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: batch_job_execution_context batch_job_execution_context_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.batch_job_execution_context
    ADD CONSTRAINT batch_job_execution_context_pkey PRIMARY KEY (job_execution_id);


--
-- Name: batch_job_execution batch_job_execution_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.batch_job_execution
    ADD CONSTRAINT batch_job_execution_pkey PRIMARY KEY (job_execution_id);


--
-- Name: batch_job_instance batch_job_instance_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.batch_job_instance
    ADD CONSTRAINT batch_job_instance_pkey PRIMARY KEY (job_instance_id);


--
-- Name: batch_step_execution_context batch_step_execution_context_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.batch_step_execution_context
    ADD CONSTRAINT batch_step_execution_context_pkey PRIMARY KEY (step_execution_id);


--
-- Name: batch_step_execution batch_step_execution_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.batch_step_execution
    ADD CONSTRAINT batch_step_execution_pkey PRIMARY KEY (step_execution_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: batch_job_instance job_inst_un; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.batch_job_instance
    ADD CONSTRAINT job_inst_un UNIQUE (job_name, job_key);


--
-- Name: patients_language patients_language_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patients_language
    ADD CONSTRAINT patients_language_pkey PRIMARY KEY (name);


--
-- Name: tests_reportimage tests_reportimage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tests_reportimage
    ADD CONSTRAINT tests_reportimage_pkey PRIMARY KEY ("reportImagePK");


--
-- Name: tests_uploadedexcel tests_uploadedexcel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tests_uploadedexcel
    ADD CONSTRAINT tests_uploadedexcel_pkey PRIMARY KEY (id);


--
-- Name: Consultation_doctorFK_id_562ea058; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Consultation_doctorFK_id_562ea058" ON public."Consultation" USING btree ("doctorFK_id");


--
-- Name: Consultation_patientFK_id_f1547344; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Consultation_patientFK_id_f1547344" ON public."Consultation" USING btree ("patientFK_id");


--
-- Name: Department_hospitalFK_id_69aeada3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Department_hospitalFK_id_69aeada3" ON public."Department" USING btree ("hospitalFK_id");


--
-- Name: Diagnosis_diseaseFK_id_8c4c2a68; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Diagnosis_diseaseFK_id_8c4c2a68" ON public."Diagnosis" USING btree ("diseaseFK_id");


--
-- Name: Diagnosis_prescriptionFK_id_6ffcb495; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Diagnosis_prescriptionFK_id_6ffcb495" ON public."Diagnosis" USING btree ("prescriptionFK_id");


--
-- Name: DiseaseParamData_diseaseParamFK_id_df554f5d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "DiseaseParamData_diseaseParamFK_id_df554f5d" ON public."DiseaseParamData" USING btree ("diseaseParamFK_id");


--
-- Name: DiseaseParam_diseaseFK_id_a8ec9576; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "DiseaseParam_diseaseFK_id_a8ec9576" ON public."DiseaseParam" USING btree ("diseaseFK_id");


--
-- Name: Doctor_departmentFK_id_77daee56; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Doctor_departmentFK_id_77daee56" ON public."Doctor" USING btree ("departmentFK_id");


--
-- Name: Hospital_locationFK_id_cf79899d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Hospital_locationFK_id_cf79899d" ON public."Hospital" USING btree ("locationFK_id");


--
-- Name: InOutPatient_patientFK_id_606e4b19; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "InOutPatient_patientFK_id_606e4b19" ON public."InOutPatient" USING btree ("patientFK_id");


--
-- Name: Lab_hospitalFK_id_21863a7e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Lab_hospitalFK_id_21863a7e" ON public."Lab" USING btree ("hospitalFK_id");


--
-- Name: Lab_locationFK_id_fdec5689; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Lab_locationFK_id_fdec5689" ON public."Lab" USING btree ("locationFK_id");


--
-- Name: PatientDiseaseParamData_diseaseParamDataFK_id_42c7e497; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "PatientDiseaseParamData_diseaseParamDataFK_id_42c7e497" ON public."PatientDiseaseParamData" USING btree ("diseaseParamDataFK_id");


--
-- Name: PatientDiseaseParamData_patientFK_id_8a6eb2c0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "PatientDiseaseParamData_patientFK_id_8a6eb2c0" ON public."PatientDiseaseParamData" USING btree ("patientFK_id");


--
-- Name: Patient_languages_language_id_9d5226c6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Patient_languages_language_id_9d5226c6" ON public."Patient_languages" USING btree (language_id);


--
-- Name: Patient_languages_language_id_9d5226c6_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Patient_languages_language_id_9d5226c6_like" ON public."Patient_languages" USING btree (language_id varchar_pattern_ops);


--
-- Name: Patient_languages_patient_id_09d66b1d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Patient_languages_patient_id_09d66b1d" ON public."Patient_languages" USING btree (patient_id);


--
-- Name: PrescribedMedicine_medicineFK_id_ff78b732; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "PrescribedMedicine_medicineFK_id_ff78b732" ON public."PrescribedMedicine" USING btree ("medicineFK_id");


--
-- Name: PrescribedMedicine_prescriptionFK_id_6671857d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "PrescribedMedicine_prescriptionFK_id_6671857d" ON public."PrescribedMedicine" USING btree ("prescriptionFK_id");


--
-- Name: PrescribedTest_prescriptionFK_id_f7e62051; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "PrescribedTest_prescriptionFK_id_f7e62051" ON public."PrescribedTest" USING btree ("prescriptionFK_id");


--
-- Name: PrescribedTest_testFK_id_dffb7afa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "PrescribedTest_testFK_id_dffb7afa" ON public."PrescribedTest" USING btree ("testFK_id");


--
-- Name: ReferenceRange_testParamFK_id_c1f482e7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "ReferenceRange_testParamFK_id_c1f482e7" ON public."ReferenceRange" USING btree ("testParamFK_id");


--
-- Name: ReportParamData_reportFK_id_0662d7a5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "ReportParamData_reportFK_id_0662d7a5" ON public."ReportParamData" USING btree ("reportFK_id");


--
-- Name: ReportParamData_testParamFK_id_acf5217f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "ReportParamData_testParamFK_id_acf5217f" ON public."ReportParamData" USING btree ("testParamFK_id");


--
-- Name: Report_prescriptionFK_id_3bbb0342; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Report_prescriptionFK_id_3bbb0342" ON public."Report" USING btree ("prescriptionFK_id");


--
-- Name: Report_testFK_id_152ed30b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Report_testFK_id_152ed30b" ON public."Report" USING btree ("testFK_id");


--
-- Name: Residence_patientFK_id_eeb176a5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Residence_patientFK_id_eeb176a5" ON public."Residence" USING btree ("patientFK_id");


--
-- Name: TestParam_testFK_id_ac12df53; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "TestParam_testFK_id_ac12df53" ON public."TestParam" USING btree ("testFK_id");


--
-- Name: Test_labFK_id_652699bc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Test_labFK_id_652699bc" ON public."Test" USING btree ("labFK_id");


--
-- Name: Treatment_medicineFK_id_95c10ec4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Treatment_medicineFK_id_95c10ec4" ON public."Treatment" USING btree ("medicineFK_id");


--
-- Name: Treatment_patientFK_id_744b6d34; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Treatment_patientFK_id_744b6d34" ON public."Treatment" USING btree ("patientFK_id");


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: patients_language_name_55710f96_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX patients_language_name_55710f96_like ON public.patients_language USING btree (name varchar_pattern_ops);


--
-- Name: tests_reportimage_reportParamFK_id_87d5c94d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "tests_reportimage_reportParamFK_id_87d5c94d" ON public.tests_reportimage USING btree ("reportParamFK_id");


--
-- Name: Consultation Consultation_doctorFK_id_562ea058_fk_Doctor_doctorPK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Consultation"
    ADD CONSTRAINT "Consultation_doctorFK_id_562ea058_fk_Doctor_doctorPK" FOREIGN KEY ("doctorFK_id") REFERENCES public."Doctor"("doctorPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Consultation Consultation_patientFK_id_f1547344_fk_Patient_patientPK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Consultation"
    ADD CONSTRAINT "Consultation_patientFK_id_f1547344_fk_Patient_patientPK" FOREIGN KEY ("patientFK_id") REFERENCES public."Patient"("patientPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Department Department_hospitalFK_id_69aeada3_fk_Hospital_hospitalPK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Department"
    ADD CONSTRAINT "Department_hospitalFK_id_69aeada3_fk_Hospital_hospitalPK" FOREIGN KEY ("hospitalFK_id") REFERENCES public."Hospital"("hospitalPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Diagnosis Diagnosis_diseaseFK_id_8c4c2a68_fk_Disease_diseasePK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Diagnosis"
    ADD CONSTRAINT "Diagnosis_diseaseFK_id_8c4c2a68_fk_Disease_diseasePK" FOREIGN KEY ("diseaseFK_id") REFERENCES public."Disease"("diseasePK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Diagnosis Diagnosis_prescriptionFK_id_6ffcb495_fk_Prescript; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Diagnosis"
    ADD CONSTRAINT "Diagnosis_prescriptionFK_id_6ffcb495_fk_Prescript" FOREIGN KEY ("prescriptionFK_id") REFERENCES public."Prescription"("prescriptionPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: DiseaseParamData DiseaseParamData_diseaseParamFK_id_df554f5d_fk_DiseasePa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DiseaseParamData"
    ADD CONSTRAINT "DiseaseParamData_diseaseParamFK_id_df554f5d_fk_DiseasePa" FOREIGN KEY ("diseaseParamFK_id") REFERENCES public."DiseaseParam"("diseaseParamPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: DiseaseParam DiseaseParam_diseaseFK_id_a8ec9576_fk_Disease_diseasePK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DiseaseParam"
    ADD CONSTRAINT "DiseaseParam_diseaseFK_id_a8ec9576_fk_Disease_diseasePK" FOREIGN KEY ("diseaseFK_id") REFERENCES public."Disease"("diseasePK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Doctor Doctor_departmentFK_id_77daee56_fk_Department_departmentPK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Doctor"
    ADD CONSTRAINT "Doctor_departmentFK_id_77daee56_fk_Department_departmentPK" FOREIGN KEY ("departmentFK_id") REFERENCES public."Department"("departmentPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Hospital Hospital_locationFK_id_cf79899d_fk_Location_locationPK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Hospital"
    ADD CONSTRAINT "Hospital_locationFK_id_cf79899d_fk_Location_locationPK" FOREIGN KEY ("locationFK_id") REFERENCES public."Location"("locationPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: InOutPatient InOutPatient_patientFK_id_606e4b19_fk_Patient_patientPK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."InOutPatient"
    ADD CONSTRAINT "InOutPatient_patientFK_id_606e4b19_fk_Patient_patientPK" FOREIGN KEY ("patientFK_id") REFERENCES public."Patient"("patientPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Lab Lab_hospitalFK_id_21863a7e_fk_Hospital_hospitalPK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Lab"
    ADD CONSTRAINT "Lab_hospitalFK_id_21863a7e_fk_Hospital_hospitalPK" FOREIGN KEY ("hospitalFK_id") REFERENCES public."Hospital"("hospitalPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Lab Lab_locationFK_id_fdec5689_fk_Location_locationPK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Lab"
    ADD CONSTRAINT "Lab_locationFK_id_fdec5689_fk_Location_locationPK" FOREIGN KEY ("locationFK_id") REFERENCES public."Location"("locationPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: PatientDiseaseParamData PatientDiseaseParamD_diseaseParamDataFK_i_42c7e497_fk_DiseasePa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatientDiseaseParamData"
    ADD CONSTRAINT "PatientDiseaseParamD_diseaseParamDataFK_i_42c7e497_fk_DiseasePa" FOREIGN KEY ("diseaseParamDataFK_id") REFERENCES public."DiseaseParamData"("diseaseParamDataPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: PatientDiseaseParamData PatientDiseaseParamD_patientFK_id_8a6eb2c0_fk_Patient_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatientDiseaseParamData"
    ADD CONSTRAINT "PatientDiseaseParamD_patientFK_id_8a6eb2c0_fk_Patient_p" FOREIGN KEY ("patientFK_id") REFERENCES public."Patient"("patientPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Patient_languages Patient_languages_language_id_9d5226c6_fk_patients_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Patient_languages"
    ADD CONSTRAINT "Patient_languages_language_id_9d5226c6_fk_patients_" FOREIGN KEY (language_id) REFERENCES public.patients_language(name) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Patient_languages Patient_languages_patient_id_09d66b1d_fk_Patient_patientPK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Patient_languages"
    ADD CONSTRAINT "Patient_languages_patient_id_09d66b1d_fk_Patient_patientPK" FOREIGN KEY (patient_id) REFERENCES public."Patient"("patientPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: PrescribedMedicine PrescribedMedicine_medicineFK_id_ff78b732_fk_Medicine_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PrescribedMedicine"
    ADD CONSTRAINT "PrescribedMedicine_medicineFK_id_ff78b732_fk_Medicine_" FOREIGN KEY ("medicineFK_id") REFERENCES public."Medicine"("medicinePK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: PrescribedMedicine PrescribedMedicine_prescriptionFK_id_6671857d_fk_Prescript; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PrescribedMedicine"
    ADD CONSTRAINT "PrescribedMedicine_prescriptionFK_id_6671857d_fk_Prescript" FOREIGN KEY ("prescriptionFK_id") REFERENCES public."Prescription"("prescriptionPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: PrescribedTest PrescribedTest_prescriptionFK_id_f7e62051_fk_Prescript; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PrescribedTest"
    ADD CONSTRAINT "PrescribedTest_prescriptionFK_id_f7e62051_fk_Prescript" FOREIGN KEY ("prescriptionFK_id") REFERENCES public."Prescription"("prescriptionPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: PrescribedTest PrescribedTest_testFK_id_dffb7afa_fk_Test_testPK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PrescribedTest"
    ADD CONSTRAINT "PrescribedTest_testFK_id_dffb7afa_fk_Test_testPK" FOREIGN KEY ("testFK_id") REFERENCES public."Test"("testPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Prescription Prescription_consultationFK_id_b8be6702_fk_Consultat; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Prescription"
    ADD CONSTRAINT "Prescription_consultationFK_id_b8be6702_fk_Consultat" FOREIGN KEY ("consultationFK_id") REFERENCES public."Consultation"("consultationPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ReferenceRange ReferenceRange_testParamFK_id_c1f482e7_fk_TestParam_testParamPK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ReferenceRange"
    ADD CONSTRAINT "ReferenceRange_testParamFK_id_c1f482e7_fk_TestParam_testParamPK" FOREIGN KEY ("testParamFK_id") REFERENCES public."TestParam"("testParamPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ReportParamData ReportParamData_reportFK_id_0662d7a5_fk_Report_reportPK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ReportParamData"
    ADD CONSTRAINT "ReportParamData_reportFK_id_0662d7a5_fk_Report_reportPK" FOREIGN KEY ("reportFK_id") REFERENCES public."Report"("reportPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ReportParamData ReportParamData_testParamFK_id_acf5217f_fk_TestParam; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ReportParamData"
    ADD CONSTRAINT "ReportParamData_testParamFK_id_acf5217f_fk_TestParam" FOREIGN KEY ("testParamFK_id") REFERENCES public."TestParam"("testParamPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Report Report_prescriptionFK_id_3bbb0342_fk_Prescript; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Report"
    ADD CONSTRAINT "Report_prescriptionFK_id_3bbb0342_fk_Prescript" FOREIGN KEY ("prescriptionFK_id") REFERENCES public."Prescription"("prescriptionPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Report Report_testFK_id_152ed30b_fk_Test_testPK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Report"
    ADD CONSTRAINT "Report_testFK_id_152ed30b_fk_Test_testPK" FOREIGN KEY ("testFK_id") REFERENCES public."Test"("testPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Residence Residence_patientFK_id_eeb176a5_fk_Patient_patientPK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Residence"
    ADD CONSTRAINT "Residence_patientFK_id_eeb176a5_fk_Patient_patientPK" FOREIGN KEY ("patientFK_id") REFERENCES public."Patient"("patientPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: TestParam TestParam_testFK_id_ac12df53_fk_Test_testPK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TestParam"
    ADD CONSTRAINT "TestParam_testFK_id_ac12df53_fk_Test_testPK" FOREIGN KEY ("testFK_id") REFERENCES public."Test"("testPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Test Test_labFK_id_652699bc_fk_Lab_labPK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Test"
    ADD CONSTRAINT "Test_labFK_id_652699bc_fk_Lab_labPK" FOREIGN KEY ("labFK_id") REFERENCES public."Lab"("labPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Treatment Treatment_medicineFK_id_95c10ec4_fk_Medicine_medicinePK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Treatment"
    ADD CONSTRAINT "Treatment_medicineFK_id_95c10ec4_fk_Medicine_medicinePK" FOREIGN KEY ("medicineFK_id") REFERENCES public."Medicine"("medicinePK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Treatment Treatment_patientFK_id_744b6d34_fk_Patient_patientPK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Treatment"
    ADD CONSTRAINT "Treatment_patientFK_id_744b6d34_fk_Patient_patientPK" FOREIGN KEY ("patientFK_id") REFERENCES public."Patient"("patientPK") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: batch_job_execution_context job_exec_ctx_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.batch_job_execution_context
    ADD CONSTRAINT job_exec_ctx_fk FOREIGN KEY (job_execution_id) REFERENCES public.batch_job_execution(job_execution_id);


--
-- Name: batch_job_execution_params job_exec_params_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.batch_job_execution_params
    ADD CONSTRAINT job_exec_params_fk FOREIGN KEY (job_execution_id) REFERENCES public.batch_job_execution(job_execution_id);


--
-- Name: batch_step_execution job_exec_step_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.batch_step_execution
    ADD CONSTRAINT job_exec_step_fk FOREIGN KEY (job_execution_id) REFERENCES public.batch_job_execution(job_execution_id);


--
-- Name: batch_job_execution job_inst_exec_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.batch_job_execution
    ADD CONSTRAINT job_inst_exec_fk FOREIGN KEY (job_instance_id) REFERENCES public.batch_job_instance(job_instance_id);


--
-- Name: batch_step_execution_context step_exec_ctx_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.batch_step_execution_context
    ADD CONSTRAINT step_exec_ctx_fk FOREIGN KEY (step_execution_id) REFERENCES public.batch_step_execution(step_execution_id);


--
-- Name: tests_reportimage tests_reportimage_reportParamFK_id_87d5c94d_fk_ReportPar; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tests_reportimage
    ADD CONSTRAINT "tests_reportimage_reportParamFK_id_87d5c94d_fk_ReportPar" FOREIGN KEY ("reportParamFK_id") REFERENCES public."ReportParamData"("reportParamFK") DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

